# Site settings
title: Pentest Writeups | Hugo Beaulieu
email: hugo@hugo.quebec
description: >-
  A collection of writeups for HackTheBox and CTF competitions.
baseurl: ""
url: "https://beaulieuhugo97.github.io"
github_username: beaulieuhugo97

# Theme
theme: jekyll-theme-hacker

# Plugins
plugins:
  - jekyll-feed
